#!/usr/bin/env bash
cd sftp
echo "Building simple sftpserver for integration tests."
docker build -t docker.dbc.dk/simplesftpserver:devel .
if [[ ! -z "$BUILD_NUMBER" ]]; then
    docker tag docker.dbc.dk/simplesftpserver:devel docker.dbc.dk/simplesftpserver:${BRANCH_NAME}-${BUILD_NUMBER}
fi